version: '2'

services:
  main:
    image: 'mitra-main:latest'
    build:
      context: .
    container_name: main
    ports:
      - 8700:8700
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mitra
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=mitra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
