version: '2'

services:
  client:
    image: mozevil/mitra-client:latest
    container_name: client
    ports:
      - 8701:8701
    environment:
      - APP_MAINAPPURL=http://main:8700

  main:
    image: mozevil/mitra-main:latest
    container_name: main
    ports:
      - 8700:8700
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mitra
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_DB=mitra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

